import { Poppins, Saira } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

// Google fonts
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const saira = Saira({
  variable: "--font-saira",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const segoeUI = localFont({
  src: [
    {
      path: "../../public/fonts/SegoeUI.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-segoe-ui",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${saira.variable} ${segoeUI.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
